### ISSUE TITLE
Missing 'ButtonGroup'

### ISSUE THREAD

**Issue by Jogai** [F1nnM/unplugin-primevue-resolver#1]
Docs: https://primevue.org/button/#buttongroup
If you click to the code on stackblitz you can see the import

**Comment by Jogai** [comment]
Awesome, thanks. Is it deliberate yet unreleased? (not in a hurry, because I have a workaround anyway)

**Comment by F1nnM** [comment]
Ah, I started and then got distracted, sorry. It's published now. Version 1.0.6

**Comment by Jogai** [comment]
Understandable, thanks.
